# Maven
trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: AWS
  - name: AWS_ACCESS_KEY_ID
    value: $(aws.access.key.id)
  - name: AWS_SECRET_ACCESS_KEY
    value: $(aws.secret.access.key)
  - name: AWS_REGION
    value: $(aws.region)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'
      script: pip install aws-sam-cli

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

  - task: CmdLine@2
    inputs:
      script: 'mvn clean install'
      #workingDirectory: # Optional
      #failOnStderr: false # Optional
  - task: CmdLine@2
    inputs:
      script: 'sam build ; sam deploy --region sa-east-1 --stack-name request-counter-stack --s3-bucket request-counter-bucket --capabilities CAPABILITY_IAM --debug'
      #workingDirectory: # Optional
      #failOnStderr: false # Optional

