# Maven
trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: CloudFormationCreateOrUpdateStack@1
    inputs:
      awsCredentials: 'AWS - Mateus'
      regionName: 'sa-east-1'
      stackName: 'RequestCounter'
      templateSource: 'file'
      templateFile: 'template.yml'
      s3BucketName: 'request-counter-bucket'
      useChangeSet: true
      changeSetName: 'request-counter-changeset'
      capabilityAutoExpand: true
      onFailure: 'DELETE'
      logRequest: true
      logResponse: true
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
