# Maven
trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: AWS

steps:
  - script: set AWS_ACCESS_KEY_ID=$(AWS_REGION)
  - script: set AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID) # uses macro syntax
  - script: set AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
  - script: sudo aws configure

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'
      script: pip install aws-sam-cli

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

  - task: CmdLine@2
    inputs:
      script: 'mvn clean install'
      #workingDirectory: # Optional
      #failOnStderr: false # Optional
  - task: CmdLine@2
    inputs:
      script: 'sam deploy --region sa-east-1 --stack-name request-counter-stack --s3-bucket request-counter-bucket --capabilities CAPABILITY_IAM --debug'
      #workingDirectory: # Optional
      #failOnStderr: false # Optional

